fadeev visdoravlivai((
frogitcher/oop_misis_2022 pull request #10
Opened 2022-03-12 07:58 UTC by medjidi

2022-03-13 18:59 UTC, frogitcher commented on magomedov_m_m/hello_world/CmakeLists.txt
> +	hello_world.h
А сюда не нужно hello_world.cpp добавить?

2022-03-13 19:11 UTC, frogitcher requested changes
Нужно переименовать все CmakeLists.txt в CMakeLists.txt
все остальное ок

2022-03-13 19:40 UTC, medjidi commented
вроде нет, во всяком случае, на видео его мы не добавляли. Да и не создавали13.03.2022, 21:59, "frogitcher" ***@***.***>:
@frogitcher commented on this pull request.



In magomedov_m_m/hello_world/CmakeLists.txt:
> @@ -0,0 +1,11 @@
+cmake_minimum_required(VERSION 3.0)
+
+project(project)
+
+add_executable(main 
+	main.cpp 
+	hello_world.h

А сюда не нужно hello_world.cpp добавить?

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
-- мед

2022-03-13 20:02 UTC, frogitcher requested changes

2022-03-13 20:02 UTC, frogitcher commented on magomedov_m_m/hello_world/CMakeLists.txt
> +	hello_world.cpp
hello_world.cpp отсутствует, поэтому не собирается

2022-04-07 20:49 UTC, frogitcher commented
В общем, пока закрываю ПР. Если нужно будет - переоткрой

2022-04-07 20:49 UTC, closed without merging