add rational numbers :/
frogitcher/oop_misis_2022 pull request #105
Opened 2022-04-17 00:42 UTC by KoshkinPV

2022-04-18 08:53 UTC, storst1 requested changes

2022-04-18 08:53 UTC, storst1 commented on koshkin_p_v/rational/rational/rational.cpp
> +    return !((num == rhs.num) && (den == rhs.den));
Можно просто !(*this == rhs)

2022-04-18 08:53 UTC, storst1 commented on koshkin_p_v/rational/rational/rational.cpp
> +    return !((num * rhs.den) > (den * rhs.num));
Можно !(*this > oth)

2022-04-18 08:53 UTC, storst1 commented on koshkin_p_v/rational/rational/rational.cpp
> +    return !((num * rhs.den) < (den * rhs.num));
Можно !(*this < oth)

2022-04-18 08:53 UTC, storst1 commented on koshkin_p_v/rational/rational/rational.cpp
> +int lcm(int x, int y)
lcm нигде потом не используется

2022-04-18 08:53 UTC, storst1 commented on koshkin_p_v/rational/rational/rational.cpp
> +        throw domain_error("Division can`t be equal to zero!");
Divisor*

2022-04-18 16:45 UTC, storst1 approved these changes

2022-04-19 10:51 UTC, frogitcher approved these changes

2022-04-19 10:51 UTC, frogitcher commented on koshkin_p_v/rational/rational/test.cpp
> +    CHECK((--b == Rational(-5, 13))==true);
Можно проверить, что a++ возвращает до изменения

2022-04-19 10:51 UTC, frogitcher commented on koshkin_p_v/rational/rational/test.cpp
> +    CHECK((a != d) == true);
Не обязательно дописывать 
== true
== false
Достаточно CHECK(..) в случае true
И CHECK_FALSE(..) в случае false

2022-04-19 10:54 UTC, KoshkinPV commented on koshkin_p_v/rational/rational/test.cpp
> +    CHECK((a != d) == true);
Спасибо, в следующий раз так и сделаю!

2022-04-19 21:59 UTC, merged