feat: add rational project
frogitcher/oop_misis_2022 pull request #111
Opened 2022-04-18 06:03 UTC by Ilya703

2022-05-17 23:31 UTC, ylivshits requested changes
dynamic array

2022-05-17 23:31 UTC, ylivshits commented on skobelev_i_s/dynamicArray/dynamic.cpp
> +        std::copy(data + index - 1, data + size, data + index);
Данный кусок кода будет клонировать значение ячейки data[index - 1] во всю правую часть массива. Так как надо сдвинуть все элементы на одну ячейку вправо, то надо начинать переносить значения ячеек с правого конца и идти налево до inex -ой ячейки. Это можно сделать с помощью std::copy_backward().

2022-05-17 23:31 UTC, ylivshits commented on skobelev_i_s/dynamicArray/dynamic.cpp
> +        std::copy(data + index - 1, data + size, data + index);
Данный кусок кода будет клонировать значение ячейки data[index - 1] во всю правую часть массива. Так как надо сдвинуть все элементы на одну ячейку вправо, то надо начинать переносить значения ячеек с правого конца и идти налево до inex -ой ячейки. Это можно сделать с помощью std::copy_backward().

2022-05-17 23:31 UTC, ylivshits commented on skobelev_i_s/dynamicArray/dynamic.cpp
> +    other.capacity = temp2;
можно size и capacity так же через swap реализовать

2022-05-17 23:31 UTC, ylivshits commented on skobelev_i_s/dynamicArray/dynamic.cpp
> +    other.capacity = temp2;
можно size и capacity так же через swap реализовать

2022-05-17 23:31 UTC, ylivshits commented on skobelev_i_s/dynamicArray/dynamic.cpp
> +        }
можно свернуть через std::equal()

2022-05-17 23:31 UTC, ylivshits commented on skobelev_i_s/dynamicArray/dynamic.cpp
> +        }
можно свернуть через std::equal()

2022-05-17 23:59 UTC, ylivshits requested changes
rational

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +    den = +den;
так как в знаменателе хранится натуральное число, то эта строка не нужна

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.h
> +class Rational {
хотелось бы еще перегрузить постфиксный и префиксный ++

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.h
> +    Rational operator+();
константный метод; еще Rational operator-() const надо реализовать

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +    }
не хватает нормализации

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +    den = other.GetDenominator();
можно заменить на 
num = other.num;
den = other.den;

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +    this->Normalize();
можно просто Normalize();

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +    return *this;
return Rational(*this);
аналогично в перегрузках операторов без присваивания

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +Rational& Rational::operator+=(Rational& rhs) {
можно реализовать через operator+ или наоборот

2022-05-17 23:59 UTC, ylivshits commented on skobelev_i_s/rational/rational.cpp
> +    return num * rhs.GetDenominator() > rhs.GetNumerator() * den;
можно реализовать через <=, аналогично с остальными операторами сравнения

2022-05-25 12:10 UTC, Ilya703 commented
Все исправил, залил новые pull requests

2022-05-26 20:38 UTC, closed without merging