Dynamic Array
frogitcher/oop_misis_2022 pull request #115
Opened 2022-04-21 20:29 UTC by Calliestess

2022-05-15 21:08 UTC, ylivshits requested changes

2022-05-15 21:08 UTC, ylivshits commented on efimenko_m_y/Dynamic/dynamic.cpp
> +	capacity = other.capacity;
Если other.size > capacity, тогда увеличиваем capacity,  выделяем новую память, иначе capacity не меняем

2022-05-16 16:58 UTC, ylivshits requested changes

2022-05-16 16:58 UTC, ylivshits commented on efimenko_m_y/Dynamic/dynamic.cpp
> +	std::fill(begin() + ((size <= new_size) ? size : 0),begin() + new_size, 0);
Если size > new_size, то код заполнит нулями отрезок [data, data + new_size], но тут заполнения не должно быть, надо просто укоротить массив

2022-05-20 11:09 UTC, Calliestess commented
Все изменения сделала, но я не стала изменять на std::equal, std::copy_backward и т.д, потому что у меня не получилось построить под список аргументов

2022-05-20 11:23 UTC, ylivshits commented on efimenko_m_y/Dynamic/dynamic.cpp
> +		 capacity*=2;
лучше тогда capacity = capacity*2 + 1; потому что иначе если капасити было равно нулю, то оно и останется равным нулю, а нам нужно хотя бы одно место под новый элемент

2022-05-20 11:28 UTC, ylivshits commented on efimenko_m_y/Dynamic/dynamic.cpp
> +	}
else {
  if (new_size > capacity) {
    reallocate(new_size);
  }
  std::fill(begin() + size, begin() + new_size, 0);
  size = new_size;
}

2022-05-20 11:29 UTC, ylivshits commented on efimenko_m_y/Dynamic/dynamic.cpp
> +		std::swap(data, other.data);
цикла вокруг swap(data, other.data) быть не должно

2022-05-20 13:12 UTC, ylivshits approved these changes

2022-05-21 05:43 UTC, merged