Dyn array
frogitcher/oop_misis_2022 pull request #118
Opened 2022-04-22 13:16 UTC by Seduceme69

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣶⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⠿⠟⠛⠻⣿⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣆⣀⣀⠀⣿⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠻⣿⣿⣿⠅⠛⠋⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢼⣿⣿⣿⣃⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣟⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣛⣛⣫⡄⠀⢸⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⡆⠸⣿⣿⣿⡷⠂⠨⣿⣿⣿⣿⣶⣦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣾⣿⣿⣿⣿⡇⢀⣿⡿⠋⠁⢀⡶⠪⣉⢸⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⡏⢸⣿⣷⣿⣿⣷⣦⡙⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣇⢸⣿⣿⣿⣿⣿⣷⣦⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣵⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⡁⠀⠀

2022-05-16 21:27 UTC, ylivshits requested changes
проверила пока только dynamic array

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	data = new int[size];
data = new int[capacity];

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	}
можно через std::copy()

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +			std::copy(data, data + capacity, nw_data);
std::copy(data, data + size, nw_data); 
суффикс копировать не надо

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +			capacity *= 2;
размер выделенного блока данных - capacity, тогда capacity = 1

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +		}
можно свернуть через std::equal()

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +			capacity *= 2;
можно реализовать через ResizeArray(1)

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	return at(i);;
здесь нужно просто вернуть значение ячейки без проверок, поэтому через at() делать нельзя

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	if (i >= size) {
нужно добавить i < 0

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	capacity = 0;
Нужно оставить только size = 0. Очистка динамического массива означает, что мы "выкидываем" все элементы, то есть обнуляем size. Блок памяти остается выделенным, удалять data и обнулять capacity не нужно

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	if (i >= size) {
&& (i<0)

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +		}
можно через std::copy()

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +			std::copy(data, data + capacity, nw_data);
std::copy(data, data + size, nw_data);
size=0, поэтому эту строку в принципе можно пропустить

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +		data = nwdata;
можно реализовать через ResizeArray(nwcapacity)

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	if (i >= size) {
&& (i<0)

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +		}
можно через std::copy_backward()

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	return data + size - 1;
end() - указатель на первый элемент после последнего, поэтому return data+size

2022-05-16 21:27 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	other.capacity = b;
можно через swap
std::swap(size, other.size);
std::swap(capacity, other.capacity);
std::swap(data, other.data);

2022-05-16 21:28 UTC, ylivshits requested changes

2022-05-28 07:56 UTC, Seduceme69 commented on Ten_d_s/dyn_array/dynamic_array.h
> +public:
Добавил

2022-05-29 00:34 UTC, ylivshits requested changes
Комментарии двенадцатидневной давности, за исключением тех, которые об операторе=, все еще актуальны

2022-05-29 21:05 UTC, ylivshits approved these changes

2022-05-29 21:05 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +			std::copy(data, data + size, nw_data);
надо вернуть строку int* nw_data = new int[capacity * 2]; перед копированием данных в nw_data

2022-05-29 21:05 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	if ((i >= size) && (i < 0)) {
|| (i<0)

2022-05-29 21:05 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	if ((i >= size) && (i<0) ){
||

2022-05-29 21:05 UTC, ylivshits commented on Ten_d_s/dyn_array/dynamic_array.cpp
> +	if ((i >= size) && (i<0)) {
||

2022-05-30 18:34 UTC, merged