added test_project and rational
frogitcher/oop_misis_2022 pull request #12
Opened 2022-03-14 10:15 UTC by ArtNeos

2022-03-19 20:29 UTC, frogitcher requested changes
В целом, все хорошо. Все комменты, кроме одного - минорные. Неминорный - про именование CMakeLists.txt. Если бы не это, сразу бы поставил ОК, но не мерджил бы. Написал бы, что можешь поправить и замерджить

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/CmakeLists.txt
> +add_subdirectory(rational)
Вообще не стоит записывать 2 задания в один ПР. Сейчас уже ладно

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/test_project/CmakeLists.txt
> +)
Хочется папочку все-таки назвать hello_world, чтобы 
1. было однообразие
2. когда нужно было бы писать поверх репы скрипты, было бы удобно, что у всех все называется правильно

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/test_project/main.cpp
> +  return 0;
Табы поехали кажись. Тут одни, в других местах другие.

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/rational.cpp
> +	if (rhs.num == 0) throw std::invalid_argument("Devisor can't be 0!");
Вообще не любят писать в одной строке. Еще (по крайней мере у нас) никогда не пишут ифы без фигурных скобок.

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/rational.cpp
> +	return (num * rhs.den <= rhs.num* den);
можно реализовать через >
например, так: return !(*this > rhs);

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/rational.cpp
> +	return *this;
можно сразу вернуть return *this += Rational(1);

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/rational.cpp
> +int Rational::getnumerator() const{
Лучше соблюдать однообразие в именовании методов. Например, чтобы всё начиналось с Большой буквы (у нас, например, именно так). То есть GetNumerator

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/rational.cpp
> +int Rational::getdenumerator() const{
скобочка прилипла к конст

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/rational.h
> +	Rational operator + (const Rational& rhs) const;
плюсик отлип от оператора

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/test.cpp
> +TEST_CASE("testing base ariphmetic operations") {
arithmetic

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/rational/test.cpp
> +    CHECK(Rational(7, 2).getdenumerator() == 2);
можно еще проверить, что нормализуется. Например, Rational(14, 4).GetNumerator() == 7

2022-03-19 20:29 UTC, frogitcher commented on smirnov_i_v/CmakeLists.txt
> +add_subdirectory(rational)
И все-таки это CMakeLists.txt. Иначе много у кого не будет собираться

2022-03-20 09:14 UTC, ArtNeos commented
Все замечания исправил, кроме последнего: я его заметил уже после того как запушил и теперь гит не распознает замену регистра как исправление и соответственно я его даже застейджить не могу. Тем не менее проект у меня собирался даже со старым названием, но в будущем я буду внимательнее.

2022-03-20 11:08 UTC, frogitcher approved these changes
Окаю, если получится поменять CmakeLists.txt - поменяй. Потом жми merge
Там просто:
1. Меняешь название
2. git add ..../CmakeLists.txt - это добавляем, что удалили этот файл
3. git add ..../CMakeLists.txt - это добавляем, что добавили с другим названием.

2022-03-20 13:38 UTC, merged