martynov_s_i add dynamic_array
frogitcher/oop_misis_2022 pull request #121
Opened 2022-04-23 08:24 UTC by smotrisergey

2022-04-23 10:32 UTC, frogitcher requested changes

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	delete[] data;
delete не нужен

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	delete[] data;
делит не нужне

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	data = new int[0];
урезать данные не обязательно

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	}
std::copy(data + index + 1, data + size, data + index)

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +			temp = temp2;
swap(temp, data[i])

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +}
for (size_t i = index; i < size; ++i) {
swap(data[i], value);
}

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	int* new_data = new int[capacity];
Давай будем перевыделять только тогда, когда нужно

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	other.capacity = capacity1;
swap size, capacity, data

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	}
тут не надо

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	return *(data + index);
[]

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	return false;
return size == 0

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	return true;
std::equal

2022-04-23 10:32 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	return *this;
не хотим перевыделять данные, если не нужно

2022-05-14 10:43 UTC, frogitcher requested changes

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +		data = new_data;
мб стоит перевыделение в отдельную функцию

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	}
копи

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	delete[] data;
можно не выделять память, если её и так достаточно, так же, как и в resize

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	return std::equal(data, data + size, other.data);
можно прям в одну строчку

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.h
> +	DynamicArray() = default;
нужно удалить

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.h
> +	DynamicArray(size_t lenght, int value = 0);
size_t length = 0

2022-05-14 10:43 UTC, frogitcher commented on martynov_s_i/dynamic_array/dynamic_array.h
> +	int* data = new int[0];
давай тут nullptr, иначе утекаем

2022-05-15 18:43 UTC, ylivshits requested changes
коммент про std::fill() просто как альтернатива, по остальным 2 комментариям надо исправить

2022-05-15 18:43 UTC, ylivshits commented on martynov_s_i/dynamic_array/dynamic_array.h
> +	int* end();
int* begin() const;
int* end() const;

2022-05-15 18:43 UTC, ylivshits commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +	std::copy(oth_data, oth_data + oth_capacity, new_data);
std::copy(oth_data, oth_data + oth_size, new_data); считаем, что в ячейках [oth_size, oth_capacity-1] не лежит ничего, поэтому их переносить в новую память не надо

2022-05-15 18:43 UTC, ylivshits commented on martynov_s_i/dynamic_array/dynamic_array.cpp
> +			}
можно через std::fill()

2022-05-15 19:43 UTC, ylivshits approved these changes

2022-05-16 14:11 UTC, frogitcher approved these changes

2022-05-22 07:27 UTC, merged