dynamic array
frogitcher/oop_misis_2022 pull request #122
Opened 2022-04-25 14:35 UTC by Mariiiiiiiia

2022-05-08 22:18 UTC, frogitcher approved these changes

2022-05-08 22:18 UTC, frogitcher commented on Borodkina/dynamic_array/dynamic_array.cpp
> +    }
Можно просто return size == 0

2022-05-08 22:18 UTC, frogitcher commented on Borodkina/dynamic_array/dynamic_array.cpp
> +        capacity *= 2;
Все ещё можно унести в реаллокейт

2022-05-08 22:18 UTC, frogitcher commented on Borodkina/dynamic_array/dynamic_array.cpp
> +    }
Можно через std::fill

2022-05-08 22:18 UTC, frogitcher commented on Borodkina/dynamic_array/dynamic_array.cpp
> +    if (index < 0| index>size) {
Ой-ей, тут должен быть не битовое или, а логическое (не одна палка, а две)

2022-05-08 22:18 UTC, frogitcher commented on Borodkina/dynamic_array/dynamic_array.cpp
> +     return data + size-1;
Нет. data + size.

2022-05-08 22:18 UTC, frogitcher commented on Borodkina/dynamic_array/dynamic_array.cpp
> +     return true;
Да, но можно свернуть.
Цикл можно свернуть через std::equal
Тогда вообще получится 
return size == other.size && std::equal(...)

2022-05-21 21:56 UTC, ylivshits requested changes
Stack

2022-05-21 21:56 UTC, ylivshits commented on Borodkina/stack/stack.h
> +    {
Все определения методов, конструкторов, деструктора надо вынести отсюда и вставить ниже объявлений (т.е. как в динмассиве, только подряд в одном файле)

2022-05-21 21:56 UTC, ylivshits commented on Borodkina/stack/stack.h
> +      //  for (int i = 0; i < list.size(); i++)
Закомментированные строки лучше удалять

2022-05-21 21:56 UTC, ylivshits commented on Borodkina/stack/stack.h
> +        *this=a;
Это очень много операций, так как 3 раза идет полноценное копирование. Здесь надо свапнуть указатели на голову и хвост, а также размеры стеков

2022-05-21 21:56 UTC, ylivshits commented on Borodkina/stack/stack.h
> +                if (a->value != b->value) {return false;}
Если уж пишешь содержимое ветки в фигурных скобках, то надо на отдельной строчке поставить содержимое
if (...) {
  return false;
}

2022-05-25 16:30 UTC, ylivshits approved these changes

2022-05-25 16:56 UTC, ylivshits requested changes

2022-05-25 16:56 UTC, ylivshits commented on Borodkina/stack/stack.h
> +    head = stack.head;
Я не заметила это место: весь стек, который лежал в this до перенаправления указателей, надо удалить

2022-05-26 20:14 UTC, ylivshits approved these changes

2022-05-27 06:58 UTC, merged