Rusakov Stack
frogitcher/oop_misis_2022 pull request #123
Opened 2022-04-27 22:19 UTC by ElMarcuse

2022-05-20 22:42 UTC, ylivshits requested changes

2022-05-20 22:42 UTC, ylivshits commented on rusakov/Stack/Stack.cpp
> +﻿#include <iostream>
класс темплейтный, поэтому все определения методов и конструкторов надо вставить в хэдер ниже объявлений

2022-05-20 22:42 UTC, ylivshits commented on rusakov/Stack/Stack.cpp
> +    size--;
Если будем удалять последний элемент, то по коду выйдет, что после удаления head = nullptr, size = 0, а tail будет смотреть на несуществующий элемент, который мы только что удалили

2022-05-20 22:42 UTC, ylivshits commented on rusakov/Stack/Stack.cpp
> +    }
если other.size==0, то текущий стек надо очистить

2022-05-26 21:29 UTC, ylivshits requested changes

2022-05-26 21:29 UTC, ylivshits commented on rusakov/Stack/Stack.h
> +        delete tail;
эта строка не нужна, т.к. элемента уже не существует

2022-05-26 21:29 UTC, ylivshits commented on rusakov/Stack/Stack.h
> +        clear();
здесь это не нужно

2022-05-26 21:29 UTC, ylivshits commented on rusakov/Stack/Stack.h
> +    if(other.size != 0){
Если other.size==0, то текущий стек надо очистить. Для этого clear() надо поставить перед ифом

2022-05-28 00:18 UTC, ElMarcuse commented on rusakov/Stack/Stack.h
> +    if(other.size != 0){
Исправил

2022-05-29 00:29 UTC, ylivshits approved these changes

2022-05-29 21:37 UTC, merged