goloviznin_m_a added rationals
frogitcher/oop_misis_2022 pull request #124
Opened 2022-04-28 08:18 UTC by slivoviy

2022-05-19 12:52 UTC, ylivshits requested changes

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/CMakeLists.txt
> +add_executable(rational rational.cpp rational.h)
это можно опустить

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/CMakeLists.txt
> +add_executable(test_rational test.cpp rational.cpp)
сюда нужно добавить rational.h

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.h
> +
Rational operator+(const Rational &rhs) const;
все 4 константные

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +    denum = rhs.GetDenum();
можно заменить на 
    num = rhs.num;
    denum = rhs.denum;

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +Rational Rational::operator+(const Rational &rhs) {
const

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +    int num_1 = GetNum() * (common / GetDenum());
можно заменить на int num_1 = num * (common / denum);

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +    *this = result;
можно сократить до 
num = num * common / denum + rhs.num * common / rhs.denum;
denum = common;
return *this;

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +    result.Normalize();
При создании экземпляра Rational(num, denum) вызывается Normalize(), так что здесь строку можно опустить (аналогично в +=, -=, *=)

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +    return *this;
return Rational(*this);

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +    return *this;
return Rational(*this);

2022-05-19 12:52 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
> +bool Rational::operator>(const Rational &rhs) const {
можно реализовать через <=, аналогично остальные

2022-05-20 12:24 UTC, slivoviy commented on Golovznin_M_A/rational_numbers/CMakeLists.txt
> +add_executable(rational rational.cpp rational.h)
> это можно опустить

без этой строчки перестают работать стдшные функции lcm и gcd

2022-05-20 13:19 UTC, ylivshits requested changes

2022-05-20 13:19 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/CMakeLists.txt
> +add_executable(rational rational.cpp rational.h)
ок

2022-05-20 13:19 UTC, ylivshits commented on Golovznin_M_A/rational_numbers/rational.cpp
>      num *= -1;
менять число нельзя, можно сделать return Rational(-num, denum);

2022-05-26 20:48 UTC, ylivshits approved these changes

2022-05-27 15:52 UTC, merged