dynamic_strijakov
frogitcher/oop_misis_2022 pull request #131
Opened 2022-05-03 19:37 UTC by triflt

2022-05-16 15:01 UTC, ylivshits requested changes

2022-05-16 15:01 UTC, ylivshits commented on strijakov/dynamic/dynamic.cpp
> +	}
можно через std::copy()

2022-05-16 15:01 UTC, ylivshits commented on strijakov/dynamic/dynamic.cpp
> +    return data+size-1;
end() - указатель на первый элемент после последнего, поэтому return data+size

2022-05-16 19:17 UTC, ylivshits approved these changes

2022-05-17 09:47 UTC, frogitcher approved these changes

2022-05-19 21:09 UTC, merged