dynamic_array_1.0
frogitcher/oop_misis_2022 pull request #132
Opened 2022-05-03 19:51 UTC by sheep-shaun

2022-05-16 15:11 UTC, ylivshits commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +        }
можно через std::copy()

2022-05-16 20:18 UTC, sheep-shaun commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +    }
Исправил

2022-05-16 20:18 UTC, sheep-shaun commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +    if (new_size > size) {
Исправил

2022-05-16 20:18 UTC, sheep-shaun commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +    size = new_size;
Исправил

2022-05-16 20:18 UTC, sheep-shaun commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +    }
Исправил

2022-05-16 20:18 UTC, sheep-shaun commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +        }
Исправил

2022-05-16 21:02 UTC, ylivshits requested changes

2022-05-16 21:02 UTC, ylivshits commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +    for (int i = size; i < new_size; i++) {
for (int i = 0; i < new_size; i++)

2022-05-19 20:57 UTC, sheep-shaun commented on Kashpar_E_E/dynamic_array/dynamic_array.cpp
> +    for (int i = size; i < new_size; i++) {
Исправил

2022-05-19 23:50 UTC, ylivshits approved these changes

2022-05-20 00:00 UTC, frogitcher approved these changes

2022-05-20 09:09 UTC, merged