dynamic
frogitcher/oop_misis_2022 pull request #139
Opened 2022-05-13 11:51 UTC by zokost

2022-05-16 18:05 UTC, ylivshits requested changes

2022-05-16 18:05 UTC, ylivshits commented on zorin_k_a/dynamic/dynamic.cpp
> +    ++size;
лучше через resize(++size), т.к. иначе останется не обработанным случай capacity == size

2022-05-16 18:05 UTC, ylivshits commented on zorin_k_a/dynamic/dynamic.cpp
> +    }
можно через std::copy_backward()

2022-05-16 18:05 UTC, ylivshits commented on zorin_k_a/dynamic/dynamic.cpp
> +    std::fill(begin(),begin()+_size, value);
нужно добавить reallocate(_size), assign работает по аналогии с resize

2022-05-19 23:11 UTC, ylivshits approved these changes

2022-05-19 23:59 UTC, frogitcher approved these changes

2022-05-20 13:24 UTC, merged