adding dynanmic array
frogitcher/oop_misis_2022 pull request #141
Opened 2022-05-16 10:35 UTC by larrriiin

2022-05-16 18:50 UTC, ylivshits requested changes

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.h
> +            return std::equal<int*, int*>(data, data + size, rhs.data);
return (size==rhs.size && std::equal(...))

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.h
> +        inline friend void Reallocate(DynamicArray& da, int64_t new_size) {
если метод внутри класса, зачем его делать friend, если ему и так доступно все из private

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    data = new_data;
эти строки надо засунуть в ветку if (new_size > capacity), т.к. в ветке else выделять новый блок памяти не нужно; если выделяем память, надо не забыть обновить capacity

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    }
можно заменить на std::copy()

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    std::fill(begin() + ((size <= new_size) ? size : 0), begin() + new_size, value);
Если size > new_size, то код заполнит нулями отрезок [data, data + new_size], но тут заполнения не должно быть, надо просто укоротить массив

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +        reallocate(size);
1. Не reallocate(size), а reallocate(capacity);
2. Лучше сделать resize(++capacity). Если size == capacity && capacity != 0, то мы зайдем в reallocate(size), не попадем в ветку с выделением новой памяти, т.к. new_size == capacity, и класть еще один элемент будет некуда

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    }
Данный кусок кода будет клонировать значение ячейки data[index] во всю правую часть массива. Так как надо сдвинуть все элементы на одну ячейку вправо, то надо начинать переносить значения ячеек с правого конца и идти налево до i-ой ячейки. Это можно сделать с помощью std::copy_backward().

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    if (i >= size) {
&& (i < 0)

2022-05-16 18:50 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    capacity = rhs.capacity;
Если rhs.size > capacity, тогда увеличиваем capacity, выделяем новую память, иначе capacity не меняем. Можно использовать resize(rhs.size)

2022-05-17 21:52 UTC, ylivshits requested changes

2022-05-17 21:52 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.h
> +        }
константные методы

2022-05-19 10:31 UTC, ylivshits requested changes

2022-05-19 10:31 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    data = new_data;
надо заменить на 
 if (new_cap > capacity) {
    int* new_data = new int[new_cap];
    std::copy(data, data + size, new_data);
    delete[] data;
    data = new_data;
    capacity = new_cap;
}
else {
   // блок памяти нужно выделять заново, только если new_cap>capacity
}

При вызове метода reallocate(...) снаружи не происходит обработки, когда не надо перевыделять память, так что иф надо оставить здесь.
Перед тем, как в data положить новый указатель, надо стереть текущую дата, что и было в предыдущей версии кода. 
Если мы все-таки выделяем новую память, то capacity надо обновить на new_cap

2022-05-19 10:31 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    }
Строки 99-105: 
Здесь надо либо написать 
if (size == capacity) {
   resize(++capacity); 
}
либо 
if (size == capacity) {
   reallocate(capacity+1); 
   ++size;
}
Тогда строчку 106 (++size) надо удалить совсем.

2022-05-19 10:31 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    data[size++] = value;
Так как в reallocate(...) изменилась логика, лучше пушбэк реализовать через инсерт, чтобы не делать одинаковые исправления и в пушбэке, и в инсерте. Если не хочется делать реализацию через инсерт, то пушбэк надо исправить аналогично инсерту (см. новые комментарии)

2022-05-19 10:31 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    capacity = rhs.capacity;
Т.к. в reallocate должна быть строчка обновления capacity? то здесь ее можно опустить

2022-05-19 10:48 UTC, larrriiin commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    data = new_data;
Метод reallocate нужен для того, чтобы выделять память вне зависимости от того, какая new_cap

2022-05-19 11:14 UTC, ylivshits requested changes
осталась последняя деталь

2022-05-19 11:14 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
>      reallocate(rhs.capacity);
Теперь раз в reallocate() нет проверки, то ее надо вставить здесь
if (rhs.size > capacity){
  reallocate(rhs.size);
}
size = rhs.size;
std::copy(rhs.data, rhs.data + size, data);
return *this;
Память выделяем заново, если текущего капасити не хватает под количество элементов rhs

2022-05-19 11:14 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
>      reallocate(rhs.capacity);
В resize и assign надо вставить такую же проверку вокруг reallocate

2022-05-20 11:13 UTC, ylivshits approved these changes

2022-05-20 11:13 UTC, ylivshits commented on larin_a_d/dynamic_array/dynamic_array.cpp
> +    if (new_size > capacity){ // Не работает
а почему не работает, не разобрался?

2022-05-20 12:58 UTC, frogitcher approved these changes

2022-05-20 13:02 UTC, merged