Add Rational and DynamicArray classes
frogitcher/oop_misis_2022 pull request #143
Opened 2022-05-18 21:44 UTC by iteamurr

2022-05-19 23:55 UTC, ylivshits requested changes
Hello world могу заапрувить после того, как создашь только с ним отдельный пулл реквест, и после нескольких исправлений структуры проекта (объясню в следующем ревью).

2022-05-20 00:20 UTC, ylivshits requested changes
Rational

2022-05-20 00:20 UTC, ylivshits commented on allayarov_t_r/CMakeLists.txt
> +
доктест надо подтащить один на всю папку с проектами (касается и проекта hello_world);
не хватает add_subdirectory(dynamic_array)

2022-05-20 00:20 UTC, ylivshits commented on allayarov_t_r/rational/rational.h
> +  int denominator_{0};
int denominator_{1};
знаменателю даже по умолчанию не полагается быть нулем

2022-05-20 00:20 UTC, ylivshits commented on allayarov_t_r/rational/rational.cpp
> +      denominator_ = denominator;
не хватает проверки знаменателя на ноль и нормализации

2022-05-20 01:04 UTC, ylivshits requested changes
Dynamic array.
Сначала проекты dynarray и rational надо исправить до конца, а потом один из них перекинуть в новый пулл реквест, тогда за готовые проекты буду ставить аппрув. А пока жду исправлений

2022-05-20 01:04 UTC, ylivshits commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +  data_ = new int[capacity_];
else {
   capacity_ = size_;
   data_ = new int[capacity_];
}
std::fill....

2022-05-20 01:04 UTC, ylivshits commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +  data_ = new int[capacity_];
else {
capacity_ = size_;
data_ = new int[capacity_];
}
std::copy....

2022-05-20 13:44 UTC, iteamurr commented on allayarov_t_r/dynamic_array/dynamic_array.h
> +  int &operator[](const size_t idx);
Как я понимаю, здесь мы реализовывали operator[] для чтения и для записи. Мне оставить только для чтения, добавив const в конец, или лучше реализовать два метода: константную для чтения и изменяемую для записи?

2022-05-20 13:44 UTC, iteamurr commented on allayarov_t_r/dynamic_array/dynamic_array.h
> +  int &at(const size_t idx);
Тот же вопрос, что и про operator[]

2022-05-20 15:57 UTC, ylivshits commented on allayarov_t_r/dynamic_array/dynamic_array.h
> +  int &operator[](const size_t idx);
Если сделать метод константным, то он будет работать и для чтения, и для записи. Константный метод означает, что внутри него не будет изменен this. Изменение ячейки data не считается изменением this. А вот если бы метод возвращал константную ссылку на интовое значение, тогда это бы означало, что менять значение ячейки нельзя.  Так что если добавить слово const к [] и at, то все будет ок

2022-05-20 16:08 UTC, iteamurr commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +    : capacity_(array.size_),
Судя по конструктору копирования у `std::vector`, `capacity` "сжимается" до размеров `size`. Я код исправлю. Но не доконца, конечно, понятно, чем эта замена лучше
![image](https://user-images.githubusercontent.com/75268876/169568010-e9536403-6464-4bce-a8d0-ca75de64cae6.png)

2022-05-20 16:13 UTC, ylivshits commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +    : capacity_(array.size_),
ок

2022-05-20 19:28 UTC, ylivshits approved these changes

2022-05-20 19:28 UTC, ylivshits commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +  if (new_size > capacity_)
можно еще укоротить (убрать первый иф, так как он есть внутри reserve)

reserve(new_size);
if (new_size > size_) {
  std::fill(data_ + size_, data_ + new_size, value);
}
size_ = new_size;

2022-05-20 19:29 UTC, ylivshits commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +  if (new_size > capacity_)
это аппрув динамического массива

2022-05-20 19:30 UTC, ylivshits approved these changes
rational

2022-05-20 19:31 UTC, iteamurr commented on allayarov_t_r/dynamic_array/dynamic_array.cpp
> +  if (new_size > capacity_)
> можно еще укоротить (убрать первый иф, так как он есть внутри reserve)
> 
> reserve(new_size); if (new_size > size_) { std::fill(data_ + size_, data_ + new_size, value); } size_ = new_size;

Сделаю

2022-05-20 19:33 UTC, ylivshits reviewed
Теперь надо создать пулл реквест, переложить туда один проект, создать другой пр, переложить туда второй проект (ничего не меняя!)

2022-05-20 19:37 UTC, iteamurr commented
> 

То есть мне отдельные Pull requests для Rational class и для DynamicArray class сделать? Я не до конца понял как я структурировать реквесты должен

2022-05-20 19:43 UTC, ylivshits reviewed
Вот так, например, это должно выглядеть
![image](https://user-images.githubusercontent.com/45213754/169600284-46ce1d3f-0106-41a9-8e27-15abdd38d8eb.png)

2022-05-20 19:45 UTC, iteamurr commented
Ага, то есть я должен на три проекта (HelloWorld, Rational, DynamicArray) разбить, под каждую свою ветку создать, а потом каждую ветку запулреквестить?

2022-05-20 19:49 UTC, ylivshits approved these changes
да, все так

2022-05-21 15:31 UTC, closed without merging