Bordukova a a
frogitcher/oop_misis_2022 pull request #19
Opened 2022-03-18 09:51 UTC by BurundukA

Adding rational

2022-03-20 11:21 UTC, frogitcher approved these changes
Есть минорные замечания. Поправиь то, что считаешь нужным и жми merge

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	den = 1;
можно вынести в список инициализации

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	den = _den;
тоже можно вынести в список иниц

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	return GetNum() * rhs.GetDen() <= rhs.GetNum() * GetDen();
можно реализовать через >
то есть return !(*this > rhs);

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	return GetNum() * rhs.GetDen() >= rhs.GetNum() * GetDen();
можно реализовать через <

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	return GetNum() * rhs.GetDen() != rhs.GetNum() * GetDen();
можно реализовать через ==

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	if (GetDen() < 0 && GetNum() >= 0) {
А если GetNum() < 0?

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	if (GetDen() < 0 && GetNum() >= 0) {
А если GetNum() < 0?

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	if (GetDen() < 0 && GetNum() >= 0) {
А если GetNum() < 0?

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	if (GetDen() < 0 && GetNum() >= 0) {
А если GetNum() < 0?

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/test.cpp
> +    std::cout << Rational(117, 237) << " - test for one operator" << std::endl;
протестить можно через stringstream
примерно так:
std::stringstream ss;
ss << Rational(1, 2);
CHECK(ss.str() == "1/2");

2022-03-20 11:21 UTC, frogitcher commented on Rational/Rational/Rational.cpp
> +	if (GetDen() < 0 && GetNum() >= 0) {
то есть наверное достаточно GetDen() < 0

2022-03-20 11:52 UTC, frogitcher requested changes
Нет. Заметил, что есть промежуточная папка. Можно без неё, если в CMakeLists.txt выше вынести просто добавление папки Rational

2022-03-20 12:11 UTC, BurundukA commented
> Нет. Заметил, что есть промежуточная папка. Можно без неё, если в CMakeLists.txt выше вынести просто добавление папки Rational

Мне исправлять данное замечание или оставить как есть?

2022-03-20 16:04 UTC, BurundukA commented
Я создала один CMakeLists.txt вместо двух и убрала доп. папку + изменила некоторые миноры

2022-04-03 11:59 UTC, frogitcher approved these changes
Закинь в папку со своим именем и можно мержить

2022-04-03 16:29 UTC, merged