F avilov din
frogitcher/oop_misis_2022 pull request #37
Opened 2022-03-26 23:28 UTC by ShockLess

2022-04-08 22:25 UTC, frogitcher requested changes
Уфф, как-то так

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +	else {
else в целом не нужен. Т.к. без него все-равно придем только тогда, когда не зайдем в if

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +			}
А если data[i] > other.data[i] тоже же должны что-то вернуть
А не возвращать нужно только, когда ==

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +		if (this->Size() < other.Size() && this[this->Size() - 1] == other[this->Size() - 1]) {
И тогда не надо на равенство проверять, т.к. в прошлом цикле всё проверим

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +{
А можно написать 1 раз и всё через реализованное писать
то есть например
a > b тоже самое, что и !(a <= b)
a < b тоже самое, что и (b > a)
и т.д.

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    }
Не, глазами смотреть не надо
Давай реализуем вывод в какой-то поток и будем со стрингстримами сравнивать
То есть 
std::stringstream ss;
ss << a;
CHECK(ss.str() == "выведенный массив");
Выводить хотим наверное всё: и size и capacity и элементы

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK(a_copy2 == Dynamic_Array(3, 4));
Хочется побольше попушбекать, чтобы точно увидеть, что массив не здох

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK_THROWS_WITH(Dynamic_Array(0).insert(1, 1); , "Index Out Of Range");
Не, все-таки можем в конец вставить

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK(a_copy2 == Dynamic_Array(2, 4));
И попопбекать побольше хочется

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK(a_copy2 == Dynamic_Array(0));
Наверное после каждого действия ххочется выводить массив и смотреть, что там в потоке

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK(a_copy2 == Dynamic_Array(0));
То есть так мы точно будем знать, что облажались, если облажались

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK(a_copy2.Empty());
Хочется для empty еще проверить, что false ывает

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    a_copy2.insert(0, 1);
Хочется побольше повставлять и в разные места

2022-04-08 22:25 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
> +    CHECK(Dynamic_Array(2)!=Dynamic_Array(3));
Хочется проверять, что false бывает
Хочется побольше вариаций

2022-04-10 21:21 UTC, ShockLess commented
обновил всё

2022-04-11 23:29 UTC, frogitcher requested changes
Есть логические ошибки, поэтому ставью Request Changes, если были бы только стилистические, то поставил бы ОК

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +{
Стоит однообразно скобки делать. Либо везде так
smth {
}
либо везде так
smth
{
}

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +		*(data + index) = *(data + index + 1);
вообще можно и data[index], data[index+1], но не важно

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic.h
> +	int* end() const;
кстати обычно методы в классе все делают с Большой Буквы. За исключением begin, end

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic.h
> +	int* end() const;
Почему в STL с маленькой - не скажу

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +	return *this;
Ой-ой. А если other.Size() <= Size(), то всё равно выделяем, хотя не должны. То есть память утекает Если перенести 115 строку внутрь ифа, то всё будет ок.

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +	}
Удобнее через equal, выглядеть должно так:
return Size() == other.Size() && equal(begin(), end(), other.begin());

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +	}
на равенство не нужно, т.к. всё равно поймем это дальше, когда пройдем весь цикл

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +			}
А если data[i] > other.data[i] то должны вернуть true. Не возвращаем только если равные

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +		if (this->Size() < other.Size() && this[this->Size() - 1] == other[this->Size() - 1]) {
&& this[this->Size() - 1] == other[this->Size() - 1]
 это условие не нужно, т.к.
1. а если размер 0?
2. если дойдем до сюда, значи оно уже выполнится

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +	}
То есть можно заменить на
```
for (int i = 0; i < std::min(Size(), other.Size()); ++i) {
  if (data[i] != other.data[i]) {
    return data[i] > other.data[i];
  }
}
return Size() > other.Size();
```

2022-04-11 23:29 UTC, frogitcher commented on fedor_avil/dynamic/dynamic_array.cpp
> +	return (*this == other || (other > *this));
Можно !(*this > other), покрасивше

2022-04-12 07:30 UTC, frogitcher approved these changes

2022-04-12 07:30 UTC, frogitcher commented on fedor_avil/dynamic/dynamic.h
> +	};
Вот такие методы красивее в одну строку видеть

2022-04-12 07:30 UTC, frogitcher commented on fedor_avil/dynamic/dynamic.h
> +	};
Тоже в одну строку красивее было бы

2022-04-12 07:30 UTC, frogitcher commented on fedor_avil/dynamic/test.cpp
>  }
А CMakeLists.txt никуда на пропали?

2022-04-16 10:55 UTC, frogitcher commented
Вмержили в другом ПРе

2022-04-16 10:55 UTC, closed without merging