adding dyn_array
frogitcher/oop_misis_2022 pull request #38
Opened 2022-03-30 08:59 UTC by ArtNeos

2022-04-11 23:48 UTC, frogitcher requested changes

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		if (_size < 0) throw std::invalid_argument("Size can't be negative");
А он и не будет отрицательным. Он ж int64_t

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
можно использовать std::copy

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
можно использовать std::copy

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
Можно reallocate(capacity == 0 ? 1 : capacity * 2)

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
Можно reallocate(capacity == 0 ? 1 : capacity * 2)

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	data = new int[0];
Не нужно. Ни удалять, ни выделять 0 размера

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	data = new int[0];
Не нужно. Ни удалять, ни выделять 0 размера

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	capacity = 0;
капасити уменьшать тоже не нужно. Пость уж будет, сколько выделили

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	capacity = 0;
капасити уменьшать тоже не нужно. Пость уж будет, сколько выделили

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	}
Да вроде и не нужно, чуть ниже в цикл не войдем просто

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	}
Да вроде и не нужно, чуть ниже в цикл не войдем просто

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return data + size - 1;
нет, end это первый восле последнего. Точно так же, как и в STL.

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return data + size - 1;
нет, end это первый восле последнего. Точно так же, как и в STL.

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	other.capacity = c;
Можно просто свапнуть через swap

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	other.capacity = c;
Можно просто свапнуть через swap

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return true;
можно через std::equal свернуть

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return true;
можно через std::equal свернуть

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	if (size != rhs.size) return false;
Очень не любят без скобок + на одной строке

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	if (size != rhs.size) return false;
Очень не любят без скобок + на одной строке

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.h
> +	int& at(int64_t i) const; //�� �� ��� � [] �� ��� ������ �� ������� ������� ������ ���� ����������
Комменты мб и подчистить

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.h
> +	int& at(int64_t i) const; //�� �� ��� � [] �� ��� ������ �� ������� ������� ������ ���� ����������
Комменты мб и подчистить

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.h
> +	void swap(DynArray& other); //������ ������� ��� ������� (������ ������� ������� � ���������)
Многие методы можно сделать inline. Всякие однострочные - точно

2022-04-11 23:48 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.h
> +	void swap(DynArray& other); //������ ������� ��� ������� (������ ������� ������� � ���������)
Многие методы можно сделать inline. Всякие однострочные - точно

2022-04-12 12:27 UTC, ArtNeos commented
Исправил все замечания, проверьте, пожалуйста

2022-04-13 20:41 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		if (_size < 0) throw std::invalid_argument("Size can't be negative");
Убрал строку

2022-04-13 20:41 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
Переписал через std::copy

2022-04-13 20:42 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
Переписал через std::copy

2022-04-13 20:42 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
Переписал

2022-04-13 20:42 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		}
Переписал

2022-04-13 20:42 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	data = new int[0];
Убрал лишнее

2022-04-13 20:42 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	data = new int[0];
Убрал лишнее

2022-04-13 20:43 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	capacity = 0;
И тут убрал

2022-04-13 20:43 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	capacity = 0;
И тут убрал

2022-04-13 20:43 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	}
Убрал

2022-04-13 20:43 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	}
Убрал

2022-04-13 20:44 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return data + size - 1;
Исправил, убрал "-1"

2022-04-13 20:44 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return data + size - 1;
Исправил, убрал "-1"

2022-04-13 20:44 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	other.capacity = c;
Исправил

2022-04-13 20:44 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	other.capacity = c;
Исправил

2022-04-13 20:44 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return true;
Свернул

2022-04-13 20:45 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return true;
Свернул

2022-04-13 20:45 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	if (size != rhs.size) return false;
Исправил

2022-04-13 20:45 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	if (size != rhs.size) return false;
Исправил

2022-04-13 20:45 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.h
> +	int& at(int64_t i) const; //�� �� ��� � [] �� ��� ������ �� ������� ������� ������ ���� ����������
Убрал комменты

2022-04-13 20:46 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.h
> +	int& at(int64_t i) const; //�� �� ��� � [] �� ��� ������ �� ������� ������� ������ ���� ����������
Убрал комменты

2022-04-13 20:46 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.h
> +	void swap(DynArray& other); //������ ������� ��� ������� (������ ������� ������� � ���������)
Не уверен, какие можно, но однострочные сделал inline

2022-04-13 20:46 UTC, ArtNeos commented on smirnov_i_v/dyn_array/dyn_array.h
> +	void swap(DynArray& other); //������ ������� ��� ������� (������ ������� ������� � ���������)
Не уверен, какие можно, но однострочные сделал inline

2022-04-14 08:22 UTC, frogitcher approved these changes

2022-04-14 08:22 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		std::fill(data, data + _size, value);
Табы с начала строки

2022-04-14 08:22 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	if (i >= size) throw std::out_of_range("Index out of array's range");
Не любят на одной строке и без скобок

2022-04-14 08:22 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		*(data + i) = *(data + i + 1);
Можно дата[i] и дата[i+1]

2022-04-14 08:22 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +		this->resize(size + 1);
Можно без this

2022-04-14 08:22 UTC, frogitcher commented on smirnov_i_v/dyn_array/dyn_array.cpp
> +	return std::equal(begin(), end(), rhs.begin());
Можно свернуть в rerurn size != rhs.size && equal...

2022-04-14 14:42 UTC, merged