adding Rational numbers
frogitcher/oop_misis_2022 pull request #39
Opened 2022-03-30 21:11 UTC by Calliestess

2022-04-03 13:15 UTC, frogitcher requested changes
Окнул бы, если б не промежуточная папка. Давай от неё избавимся

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational.cpp
> +		throw std::invalid_argument("Denominator must not be equal to zero");
Обычно не любят без скобочек

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational.cpp
> +	num(other.num)
давай на той же строке, что и :

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational.cpp
> +bool Rational:: operator<= (const Rational& rhs) const { return num * rhs.den <= den * rhs.num; }
можно через >

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational.cpp
> +		throw std::invalid_argument("Denominator must not be equal to zero");
тоже скобочки

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational.h
> +	Rational operator++();//����������
комменты можно и убрать

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational_test.cpp
> +    CHECK(+Rational(240, 40) == Rational(6));
У меня какой-то тест упал

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational_test.cpp
> +    std::cout << r;
стоит через stringstream

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational_test.cpp
> +    CHECK((Rational(1, 9) /= Rational(1, 9)) == Rational(1));
На какие-то операции тестов нет

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational_test.cpp
> +}
Хочется мб с числами побольше тесты

2022-04-03 13:15 UTC, frogitcher commented on efimenko_m_y/Rational/rational/rational_test.cpp
> +    CHECK(Rational(-1, 2) == Rational(-2, 4));
Можно еще проверить для ==false

2022-04-06 15:05 UTC, Calliestess commented
Я исправила ошибки, убрала лишнюю папку и добавила побольше тестов. Но у меня все тесты заходят, так что провалившейся не нашла

2022-04-06 23:45 UTC, frogitcher requested changes
То, что касается ++ и --, а также CMakeLists - существенно

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational_test.cpp
> +#include <rational/rational.h>
"doctest.h"
"rational.h"

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational_test.cpp
> +#include <rational/rational.h>
именно с кавычками, это важно

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational.cpp
> +}
Понял, почему тест падает:
Перепутаны префиксный и постфиксный операторы ++ и --.

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational_test.cpp
> +    in >> r;
in-то пустой, из него в r ничего не считывается

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational_test.cpp
> +    out << r;
тут нужно проверить, что в out действительно записалось так, как мы хотели.
То есть out.str() == "27/3"

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational_test.cpp
> +    in >> r;
можно поправить, если инициализировать std::istringstream in("27/3");

2022-04-06 23:45 UTC, frogitcher commented on efimenko_m_y/Rational/rational_test.cpp
> +    in >> t;
Ну и это тоже здесь ничего не делает

2022-04-07 00:20 UTC, frogitcher commented on efimenko_m_y/Rational/rational.cpp
> +}
Нет, не совсем.
Не перепутаны. Только у сйффиксного вернуть надо Rational, у префиксного - Rational&

2022-04-07 00:20 UTC, frogitcher commented on efimenko_m_y/Rational/rational.cpp
> +}
Собственно, упало, потому что ссылка инвалидировалась

2022-04-11 23:32 UTC, frogitcher approved these changes

2022-04-11 23:32 UTC, merged