Rational by shabaev_r_a
frogitcher/oop_misis_2022 pull request #48
Opened 2022-04-03 16:48 UTC by StrausKoldun

just rational

2022-04-06 23:50 UTC, frogitcher requested changes
Давай разнесем по 2 ПР

2022-04-07 21:41 UTC, frogitcher requested changes

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/rational.cpp
> +/* in c++20 without it, we can just write only one operator <=>
можем, угу, но научиться и понять "что под капотом" -- нужно

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/rational.cpp
> +    if (num == 0) {den=1; return;}
однострочные штуки очень не любят обычно

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/rational.cpp
> +    if (den < 0) num*=-1, den*=-1;
запятые такие вообще матюкают

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/rational.cpp
> +    num/=g, den/=g;
запятые такие не надо

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/rational.cpp
> +    if (num == 0) {den=1; return;}
кстати тут хотим ж исключение кидать

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/hello_world/CmakeLists.txt
> +cmake_minimum_required(VERSION 3.0)
из этого пр хотели ж убрать эту работу, чтобы только одна была

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/hello_world/CmakeLists.txt
> +cmake_minimum_required(VERSION 3.0)
наверное надо поребейзить

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/rational.cpp
> +#include "rational.h"
CMakeLists.txt нет для рационала

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/test.cpp
> +CHECK(Rational(11, 3).getnumerator() == 7);
А почему не 11?

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/test.cpp
> +CHECK(Rational(11, 3).getdenumerator() == 2);
А почему не 3?

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/test.cpp
> +CHECK((Rational(8, 2) /= Rational(1, 2)) == Rational(8, 1));
хочется мб с числами побольше

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/test.cpp
> +CHECK(Rational(0, 3) == Rational(0, 6));
Хочется еще проверок, когда false

2022-04-07 21:41 UTC, frogitcher commented on shabaev_r_a/rational/test.cpp
> +}
Хочется еще проверять на исключения

2022-04-08 11:28 UTC, StrausKoldun commented on shabaev_r_a/rational/rational.cpp
> +/* in c++20 without it, we can just write only one operator <=>
ну вкратце там 20++ научились сами переопределять базовые операторы сравнения через == и <=>. Ну а под капотом трехпутевое сравнение как из джавы

2022-04-08 11:41 UTC, StrausKoldun commented on shabaev_r_a/rational/rational.cpp
> +    if (num == 0) {den=1; return;}
а почему при нулевом числителе мы должны вызывать исключение?

2022-04-09 11:22 UTC, frogitcher approved these changes

2022-04-09 11:22 UTC, merged