rational gavryushov
frogitcher/oop_misis_2022 pull request #53
Opened 2022-04-03 18:47 UTC by axaxaxaxaxaxaaxaxa

2022-04-07 00:42 UTC, frogitcher requested changes
важное - оператор минус, закинуть в свою папку!
полуважное - версия смаке
не особо - всё остальное

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.cpp
> +	}
табы поехали

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.cpp
> +	num = -num;
неверно. После операции число изменится насовсем, что не должно быть

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.cpp
> +	return num * rhs.den <= rhs.num * den;
можно через >

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.cpp
> +	return num * rhs.den != rhs.num * den;
можно через ==

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.cpp
> +	return *this+Rational(1);
интересный ход, да

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.h
> +
много строчек детектед

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.h
> +	//-=,*=,/=
комменты можно и убрать

2022-04-07 00:42 UTC, frogitcher commented on rational/test.cpp
> +    CHECK((Rational(4,3)/Rational(1,4))==Rational(16,3));
можно тесты с числами и побольше

2022-04-07 00:42 UTC, frogitcher commented on rational/test.cpp
> +    CHECK(Rational(5,4)!=Rational(-5,4));
можно проверить, что false вообще бывают

2022-04-07 00:42 UTC, frogitcher commented on CMakeLists.txt
> +cmake_minimum_required (VERSION 3.23.0-rc2)
Версия cmake подозрительно похожа на ту, что у Бородкиной

2022-04-07 00:42 UTC, frogitcher commented on rational/rational.cpp
> +	return *this+Rational(1);
и у Бородкиной такой же, больше ни у кого. Честно говоря, выглядит подозрительно

2022-04-07 00:42 UTC, frogitcher commented on CMakeLists.txt
> +cmake_minimum_required (VERSION 3.23.0-rc2)
Но надо бы пониже ставить, чтобы у людей собиралось

2022-04-14 10:41 UTC, frogitcher commented
Как дела?

2022-05-14 10:29 UTC, frogitcher requested changes

2022-05-14 10:29 UTC, frogitcher commented on Gavryushov/dynamic/dynamic.cpp
> +    }
в [] не нужно проверять

2022-05-14 10:29 UTC, frogitcher commented on Gavryushov/dynamic/dynamic.cpp
> +
строчечки

2022-05-14 10:29 UTC, frogitcher commented on Gavryushov/dynamic/dynamic.cpp
> +    return false;
можно просто return size == 0

2022-05-14 10:29 UTC, frogitcher commented on Gavryushov/dynamic/dynamic.cpp
> +}
лучше посвапать по полям

2022-05-14 10:29 UTC, frogitcher commented on Gavryushov/dynamic/dynamic.cpp
> +    std::copy(data+index,data+size-1,data+index+1);
надо справа налево

2022-05-14 10:29 UTC, frogitcher commented on Gavryushov/rational/rational.cpp.bak
> +#include "rational.h"
Надо убрать этот файл

2022-05-20 13:10 UTC, ylivshits requested changes
begin() и end() в динмассиве должны быть константными.
А почему в show all changes не показываются изменения из последнего коммита?

2022-05-20 13:10 UTC, ylivshits commented on Gavryushov/dynamic/dynamic.cpp
> +    }
можно через std::copy_backward()

2022-05-26 23:25 UTC, ylivshits approved these changes

2022-05-26 23:30 UTC, ylivshits approved these changes
rational

2022-05-28 16:33 UTC, ylivshits approved these changes

2022-05-28 16:51 UTC, ylivshits approved these changes
stack

2022-05-28 16:51 UTC, ylivshits commented on Gavryushov/stack/stack.h
> +	}
можно написать Clear(), раз уж он есть

2022-05-28 16:51 UTC, ylivshits commented on Gavryushov/stack/stack.h
> +	if (size>0){
Случай нулевого size уже отработан, тип size_t беззнаковый, так что этот иф можно опустить

2022-05-28 16:51 UTC, ylivshits commented on Gavryushov/stack/stack.h
> +		throw "Nothing to pop";
лучше кидать std-шные исключения по типу invalid argument

2022-05-28 16:51 UTC, ylivshits commented on Gavryushov/stack/stack.h
> +	size = size+1;
можно ++size

2022-05-28 16:51 UTC, ylivshits commented on Gavryushov/stack/stack.h
> +	if (size==st.size && size==0){
случай неравенства длин стеков уже обработан, так что можно оставить if (size==0)

2022-05-29 19:31 UTC, frogitcher approved these changes

2022-05-29 19:46 UTC, merged