Adding dinamic array
frogitcher/oop_misis_2022 pull request #65
Opened 2022-04-05 20:03 UTC by BurundukA

Adding dynamic.cpp, dynamic.h, test.cpp

2022-04-14 10:38 UTC, frogitcher requested changes

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	, data(nullptr) {
Лучше выделять размера ноль, иначе можем удалять по нуллптр когда реаллокейтим

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +		throw std::invalid_argument("Size must be >0!");
Не будет, тк сайзт

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	, data(nullptr) {
И постоянно надо следить 
а не нуллптр ли?

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	if (size != 0) {
Не надо тк если ноль то ничего не ломается. Внутри сору цикл который просто ноль итераций сделает

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	data = nullptr;
Не надо. Достаточно размер обнулить. Пусть уж будет у нас выделенный кусок

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	if (index < 0 || index >= size) {
Не может меньше нуля тк сайзт

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	delete[] data;
Не надо перевыдедять. Можно на имеющейся памяти сделать

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +		throw std::out_of_range("Index is out of the range!");
Не. Только если больше сайз. Можешь в конец инсертить

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	if (new_size < 0) {
Не может тк сайзт

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	return data + size  - 1;
Нет. Именно плюс сайз. Как в СТЛ

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	return data + size  - 1;
Иначе например сортить не сможем

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	return data + size  - 1;
И другие алгоритмы из СТл применять

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +		return true;
Можно свернуть через std:: equal

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	}
Нет. Проверки хотим в эт. Тут только быстро элемент

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	}
Поэтому например можно сделать этот метод inline

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	data = new_data;
Хм. Есть же create_data, который везде юзается

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.h
> +	int* Get_Data() const;
Можно эти четыре метода сделать inline

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/Dynamic.h
> +	int* end();
Можно их инлайн

2022-04-14 10:38 UTC, frogitcher commented on Bordukova_A_A/Dynamic_array/test.cpp
> +    CHECK(a[1] == 6);
Можно ещё проверить например, что работает стд сорт

2022-05-15 11:38 UTC, ylivshits requested changes

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.h
> +	Dynamic_Array& operator=(const Dynamic_Array other);
...(const Dynamic_Array& other);

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +void Dynamic_Array::push_back(int value) {
можно реализовать через insert

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	capacity = 0;
физическая память остается заполненной, так что обнулять capacity не нужно

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	}
можно заменить на std::copy()

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +		throw std::out_of_range("Index is out of the range!");
то есть если index==size, то делаем пушбэк

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +		}
можно заменить на std::copy_backward()

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +		return true;
можно все заменить на
return (size==other.size && std::equal(...))

2022-05-15 11:38 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
> +	}
можно через std::copy()

2022-05-15 14:42 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.h
> +	inline int* begin()
const

2022-05-29 00:53 UTC, ylivshits approved these changes

2022-05-29 00:53 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.cpp
>  {
index не может быть меньше нуля, т.к. size_t - беззнаковый тип

2022-05-29 00:53 UTC, ylivshits commented on Bordukova_A_A/Dynamic_array/Dynamic.h
> +	inline const int* begin()
inline const int* begin() const{}
или
inline int* begin() const{}
аналогично для end()

2022-05-29 21:38 UTC, ylivshits approved these changes

2023-09-08 16:58 UTC, closed without merging