Я в Калининграде, у меня еще нет 12
frogitcher/oop_misis_2022 pull request #69
Opened 2022-04-07 21:05 UTC by leffff

2022-04-07 21:09 UTC, frogitcher requested changes
12 может и нет, но 2 работы по 2 ПР разнести придется:)

2022-04-14 10:40 UTC, frogitcher commented
Как дела?

2022-04-16 23:13 UTC, frogitcher commented
Пока закрываю. Когда понадобится - переоткрой

2022-04-16 23:13 UTC, closed without merging

2022-05-09 18:24 UTC, leffff commented
Я заново открыл пр на hello world