rational
frogitcher/oop_misis_2022 pull request #82
Opened 2022-04-09 09:14 UTC by zokost

2022-04-10 23:19 UTC, storst1 requested changes

2022-04-10 23:19 UTC, storst1 commented on zorin_k_a/rational/rational.cpp
> +    return Rational(*this) *= rhs;
Я бы в - и + так же написал бы, чтобы уж одинаково было)

2022-04-10 23:19 UTC, storst1 commented on zorin_k_a/rational/rational.cpp
> +    return (num!=rhs.num)||(den!=rhs.den);
В целом работать будет, но еще можно вот так: return !(*this == rhs);

2022-04-10 23:19 UTC, storst1 commented on zorin_k_a/rational/rational.cpp
> +    return num * rhs.den> rhs.num;
Кажется, здесь и в операторе < забыл домножить на det, должно быть так:
return num * rhs.den >/< rhs.num * det;

2022-04-10 23:19 UTC, storst1 commented on zorin_k_a/rational/rational.h
> +
Наверное еще / и /= здесь нужны

2022-04-10 23:19 UTC, storst1 commented on zorin_k_a/rational/test.cpp
> +    CHECK((a!=Rational(11,3))==0);
Можно просто писать CHECK(a>b); без лишних скобок и ==.
Если хочешь проверить, что выражение == false можно, например, написать CHECK(!(a<b));

2022-04-10 23:19 UTC, storst1 commented on zorin_k_a/rational/test.cpp
> +}
Не хочу показаться токсиком, но перфекционист во мне требует чтобы было ровно
![image](https://user-images.githubusercontent.com/89082426/162643947-59a6073a-a8db-4313-ac60-f63cb4bb383f.png)
 и без пустых строк(
![image](https://user-images.githubusercontent.com/89082426/162643956-59a40df0-bce0-4f24-aea6-52491f185ff5.png)
![image](https://user-images.githubusercontent.com/89082426/162643969-0ac370db-cba3-4947-8c27-281af3970540.png)

2022-04-16 07:31 UTC, frogitcher commented on zorin_k_a/rational/test.cpp
> +    CHECK((a!=Rational(11,3))==0);
Кстати можно CHECK_FALSE вместо отрицания

2022-04-16 07:32 UTC, frogitcher approved these changes

2022-04-16 19:59 UTC, merged