Dynamic array implementation
frogitcher/oop_misis_2022 pull request #96
Opened 2022-04-12 17:58 UTC by storst1

2022-04-16 21:46 UTC, frogitcher requested changes

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return new T[cap];
Хм, ну вроде нам ничего не мешает писать new T[cap] где нужно. Или я чего-то не понимаю?

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	delete[] data;
Вроде ничего не мешает писать делит дата где нужно.
Или я чего-то не понимаю?

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	data = new T[len];
Иногда через Alloc, иногда через new.
Хочется единообразия

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +		data = new_data;
Есть реаллок же

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +		data = new_data;
А, или чтобы 2 раза не копировать

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +		data = nullptr;
Не, удалять данные не хотим. Давай если уж выделили, то оставим массиву сколько у него есть

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	DeleteData();
Не, не особо хотим сжимать физический размер

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +void DynArr<T>::Erase(size_t start_idx, int amount)
Можно по дефолту 1 поставить у amount

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +		Erase(new_size, size - new_size);
А не хотим просто сайз уменьшить?

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	std::swap(data[i], data[j]);
Не очень понимаю, нужно ли нам это и зачем

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return data + size - 1;
Нет. Именно плюс сайз. Чтобы как в стл. И можно было применять стлные алгоритмы

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +DynArr<T> DynArr<T>::SubArr(size_t first_idx, size_t last_idx)
А не хотим правый не включать, как в стл?

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	}
Для этого есть std::reverse

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return false;
Для этого есть std::any

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	}
Для этого есть replace_if

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	}
Для этого есть erase_if

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return cnt;
Для этого есть std::count

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return At(i);
Не. Тут хотим просто выдать референс на значение. Скорее нужно эт через [] делать

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return true;
Можно свернуть через std::equal

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return size > oth.size;
Можно просто 
return oth < *this

2022-04-16 21:46 UTC, frogitcher commented on vinnik_y_v/dynamic_array/DynArr.h
> +	return *this;
Типа как в питоне.. Ну ладно

2022-05-19 14:06 UTC, ylivshits requested changes

2022-05-19 18:09 UTC, ylivshits requested changes

2022-05-20 11:49 UTC, ylivshits approved these changes

2022-05-20 12:58 UTC, frogitcher approved these changes

2022-05-20 13:00 UTC, frogitcher approved these changes

2022-05-20 13:00 UTC, merged